FROM openjdk:10.0.1-jdk-slim


RUN apt-get update && apt-get install -y procps && apt-get install -y net-tools


COPY target/catholicon-ms-matchcard.jar catholicon-ms-matchcard.jar

EXPOSE 8080 8123

ENTRYPOINT ["/usr/bin/java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8123", "-jar", "catholicon-ms-matchcard.jar"]
